### ISSUE TITLE
Question on experiments

### ISSUE THREAD

**Issue by viet2411** [shichaoy/semantic_3d_mapping#18]
Hello,
I want to test your research on a real drone, and I'm wondering that images from monocular camera can be used on your research, because  semantic segmentation can be built from RGB images, and some light weight CNNs can run in real time on embbeded system (like you wrote in your paper). Can you answer this for me?
Thank you and best regard.

**Comment by shichaoy** [comment]
hi, @viet2411 yes you can, but it requires good depth/disparity estimation, otherwise the 3D grid map is very sparse, no use. My code it self requires to have depth image input. 

If you only have monocular camera, I think it is not easy to get a dense map. There are some paper there but I am not sure the robustness.

**Comment by viet2411** [comment]
Thank you for reply. I'm just thinking of using neural network to generate depth map and make 3d grid map from it.
I'm also intered in your new paper (Monocular Object and Plane SLAM in Structured environment). Is the code avaiable yet? I want to test it on real condition and make some more research.

**Comment by shichaoy** [comment]
@viet2411  hi the code for it is not available. object only slam is available at my github.  Object with plane is not generic enough.
